// let v1 : number=100;
// console.log(v1);
// v1 =100.22;
// console.log(v1);
// let v4 : boolean=true;
// console.log(v4);
// v4=false;
// console.log(v4);
// // let sname:string='Arbaj';
// // console.log(sname);
// let sname : string='Arbaj';
// let lname:string='Mujawar';
// console.log(sname);
// let full =sname + lname;
// console.log(full);
// full = sname + ' ' +lname;
// console.log(full);
// full = sname.concat(' ', lname);
// console.log(full);
// full=`Full Name Is : ${sname} ${lname}`;
// console.log(full); 
var sname = "Arbaj Mujawar";
console.log("input string =".concat(sname));
console.log("String In Upper caswe :".concat(sname.toUpperCase()));
console.log("String In Lower Case : ".concat(sname.toLowerCase()));
console.log("Number of Character : ".concat(sname.length));
console.log("with Trim : ".concat(sname.trim, " "));
console.log("Number Of Character With Trim : ".concat(sname.trim().length));
console.log("Index of A : ".concat(sname.indexOf('A')));
console.log("Last Index Of :".concat(sname.lastIndexOf('a'), " "));
sname = 'Arbaj Mujawar';
var Index = sname.indexOf(' ');
var firstname = sname.substring(0, Index);
console.log("Firstname : ".concat(firstname));
var lastname = sname.substring(Index + 1, sname.length);
console.log("Last name : ".concat(lastname));
